[package]
name = "photonProspects"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
tokio-tungstenite = "0.24.0"
futures-util = "0.3.31"
serde = { version = "1.0.215", features = ["derive"] }
lazy_static = "1.5.0"
csv = "1.3.1"
serde_json = "1.0.133"
serde_derive = "1.0.215"